### ISSUE TITLE
 browser.takeSnapshot is not a function

### ISSUE THREAD

**Issue by platinumtest** [klamping/wdio-applitools-service#4]
I have been attempting to use the wdio-applitools-service with the version 1.1.0 version of the eyes.webdriverio sdk this weekend using the provided sample scripts.  The scripts run, but fail on the "browser.takeSnapshot" lines:  
```
1) My Google Search should open the page:
browser.takeSnapshot is not a function
running chrome
TypeError: browser.takeSnapshot is not a function
    at Context.it (/home/chrx/Documents/bmwusa/appltools5/test/specs/demo/test.js:4:17)
    at new Promise (<anonymous>)
    at new F (/home/chrx/Documents/bmwusa/appltools5/node_modules/core-js/library/modules/_export.js:36:28)

2) My Google Search should search for something:
browser.takeSnapshot is not a function
running chrome
TypeError: browser.takeSnapshot is not a function
    at Context.it (/home/chrx/Documents/bmwusa/appltools5/test/specs/demo/test.js:10:17)
    at new Promise (<anonymous>)
    at new F (/home/chrx/Documents/bmwusa/appltools5/node_modules/core-js/library/modules/_export.js:36:28)

npm ERR! Test failed.  See above for more details.
```

Any ideas why this would fail?  I installed v1.1.0 of eyes.webdriverio and v0.2.2 of wdio-applitools-service.  
I tried installing older versions of the wdio-applitools-service but i get the same error message.  

Using eyes.webdriver.io v1.1.0 by itself does work.

Here's the .js file I ran (same as the sample script that was provided):
```
describe('My Google Search', () => {
    it('should open the page', () => {
        browser.url('http://google.com')
        browser.takeSnapshot('main page')
    })

    it('should search for something', () => {
        $('#lst-ib').addValue('WebdriverIO ❤️  Applitools')
        browser.keys('Enter')
        browser.takeSnapshot('search')
    })
})
```

**Comment by klamping** [comment]
`takeSnapshot` is not defined as a webdriverio command. try using `checkWindow` instead.

**Comment by kmnaid** [comment]
checkWindow also throws the same error.

**Comment by igerasimov23** [comment]
> checkWindow also throws the same error.

 browser.checkWindow('main page') works fine

**Comment by tulasirm** [comment]
Hi I am getting this error with wdio 5.7, could you please suggest me if am doing anything wron
Stderr:
2019-03-08T04:58:06.176Z ERROR @wdio/utils:initialiseServices: Error: Couldn't initialise "@wdio/applitools-service".
Error: Cannot find module './src/Eyes'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/prokarma/e2e/node_modules/@wdio/eyes.webdriverio/index.js:1:78)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at safeRequire (/Users/prokarma/e2e/node_modules/@wdio/utils/build/initialisePlugin.js:19:13)
    at initialisePlugin (/Users/prokarma/e2e/node_modules/@wdio/utils/build/initialisePlugin.js:46:24)
    at initialiseServices (/Users/prokarma/e2e/node_modules/@wdio/utils/build/initialiseServices.js:64:53)
    at Launcher.run (/Users/prokarma/e2e/node_modules/@wdio/cli/build/launcher.js:66:52)
    at launch (/Users/prokarma/e2e/node_modules/@wdio/cli/build/run.js:93:12)
    at run (/Users/prokarma/e2e/node_modules/@wdio/cli/build/run.js:68:12)
    at Object.run (/Users/prokarma/e2e/node_modules/@wdio/cli/build/index.js:45:20)
    at Object.<anonymous> (/Users/prokarma/e2e/node_modules/@wdio/cli/bin/wdio.js:11:21)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
[0-0] 2019-03-08T04:58:06.555Z ERROR @wdio/utils:initialiseServices: Error: Couldn't initialise "@wdio/applitools-service".
Error: Cannot find module './src/Eyes'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/prokarma/e2e/node_modules/@wdio/eyes.webdriverio/index.js:1:78)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at safeRequire (/Users/prokarma/e2e/node_modules/@wdio/utils/build/initialisePlugin.js:19:13)
    at initialisePlugin (/Users/prokarma/e2e/node_modules/@wdio/utils/build/initialisePlugin.js:46:24)
    at initialiseServices (/Users/prokarma/e2e/node_modules/@wdio/utils/build/initialiseServices.js:64:53)
    at Runner.run (/Users/prokarma/e2e/node_modules/@wdio/runner/build/index.js:88:35)
    at process.on.m (/Users/prokarma/e2e/node_modules/@wdio/local-runner/build/run.js:37:20)
    at process.emit (events.js:187:15)
    at emit (internal/child_process.js:812:12)

**Comment by klamping** [comment]
@tulasirm can you open this as a new issue, along with your package.json file and the test code you're trying to run?

**Comment by shwetaneelsharma** [comment]
@tulasirm Is there an issue logged? If yes, could you please point the issue# here as a comment. Even I am facing the same error with WebdriverIO 5.7.0.
cc @klamping
