### ISSUE TITLE
Couldn't initialise "@wdio/applitools-service".

### ISSUE THREAD

**Issue by tulasirm** [klamping/wdio-applitools-service#5]
Hi I am getting this error with wdio 5.7, could you please suggest me if am doing anything wrong?

Stderr:
2019-03-08T04:58:06.176Z ERROR @wdio/utils:initialiseServices: Error: Couldn't initialise "@wdio/applitools-service".
Error: Cannot find module './src/Eyes'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
at Function.Module._load (internal/modules/cjs/loader.js:513:25)
at Module.require (internal/modules/cjs/loader.js:643:17)
at require (internal/modules/cjs/helpers.js:22:18)
at Object. (/Users/prokarma/e2e/node_modules/@wdio/eyes.webdriverio/index.js:1:78)
at Module._compile (internal/modules/cjs/loader.js:707:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
at Module.load (internal/modules/cjs/loader.js:605:32)
at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
at Function.Module._load (internal/modules/cjs/loader.js:536:3)
at safeRequire (/Users/prokarma/e2e/node_modules/@wdio/utils/build/initialisePlugin.js:19:13)
at initialisePlugin (/Users/prokarma/e2e/node_modules/@wdio/utils/build/initialisePlugin.js:46:24)
at initialiseServices (/Users/prokarma/e2e/node_modules/@wdio/utils/build/initialiseServices.js:64:53)
at Launcher.run (/Users/prokarma/e2e/node_modules/@wdio/cli/build/launcher.js:66:52)
at launch (/Users/prokarma/e2e/node_modules/@wdio/cli/build/run.js:93:12)
at run (/Users/prokarma/e2e/node_modules/@wdio/cli/build/run.js:68:12)
at Object.run (/Users/prokarma/e2e/node_modules/@wdio/cli/build/index.js:45:20)
at Object. (/Users/prokarma/e2e/node_modules/@wdio/cli/bin/wdio.js:11:21)
at Module._compile (internal/modules/cjs/loader.js:707:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
[0-0] 2019-03-08T04:58:06.555Z ERROR @wdio/utils:initialiseServices: Error: Couldn't initialise "@wdio/applitools-service".
Error: Cannot find module './src/Eyes'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
at Function.Module._load (internal/modules/cjs/loader.js:513:25)
at Module.require (internal/modules/cjs/loader.js:643:17)
at require (internal/modules/cjs/helpers.js:22:18)
at Object. (/Users/prokarma/e2e/node_modules/@wdio/eyes.webdriverio/index.js:1:78)
at Module._compile (internal/modules/cjs/loader.js:707:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
at Module.load (internal/modules/cjs/loader.js:605:32)
at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
at Function.Module._load (internal/modules/cjs/loader.js:536:3)
at safeRequire (/Users/prokarma/e2e/node_modules/@wdio/utils/build/initialisePlugin.js:19:13)
at initialisePlugin (/Users/prokarma/e2e/node_modules/@wdio/utils/build/initialisePlugin.js:46:24)
at initialiseServices (/Users/prokarma/e2e/node_modules/@wdio/utils/build/initialiseServices.js:64:53)
at Runner.run (/Users/prokarma/e2e/node_modules/@wdio/runner/build/index.js:88:35)
at process.on.m (/Users/prokarma/e2e/node_modules/@wdio/local-runner/build/run.js:37:20)
at process.emit (events.js:187:15)
at emit (internal/child_process.js:812:12)

**Comment by klamping** [comment]
Can you post your package.json file and the test code you're trying to run?

**Comment by tulasirm** [comment]
sorry for the delayed reply, here it is...

{
  "name": "webdriver-typescript",
  "version": "1.0.0",
  "description": "This project will show you how to start your UI Automation Test with WebdriverIO and TypeScript",
  "main": "index.js",
  "scripts": {
    "prettier": "./node_modules/.bin/prettier --write ./test/**/*.ts ./test/**/*.js",
    "connect-adb": "adb connect borg10.matrix.tmo.io:15005",
    "start-appium": "./node_modules/.bin/appium",
    "clean-report": "./node_modules/.bin/rimraf allure-report allure-results",
    "run-report": "./node_modules/.bin/allure generate allure-results && ./node_modules/.bin/allure open",
    "mochatest-sauce": "npm run prettier && ./node_modules/.bin/wdio ./config/wdio.mocha.sbox.conf.js",
    "mochatest-local": "npm run prettier && ./node_modules/.bin/wdio ./config/wdio.mocha.local.conf.js",
    "mochatest-cxlab": "npm run prettier && npm run connect-adb && ./node_modules/.bin/wdio ./config/wdio.mocha.cxlab.conf.js",
    "cucumbertest-sauce": "npm run prettier && ./node_modules/.bin/wdio ./config/wdio.cucumber.sauce.conf.js",
    "cucumbertest-local": "npm run prettier && ./node_modules/.bin/wdio ./config/wdio.cucumber.local.conf.js",
    "cucumbertest-cxlab": "npm run prettier && ./node_modules/.bin/wdio ./config/wdio.cucumber.cxlab.conf.js",
    "mocha-local-report": "npm run mochatest-local ; npm run run-report",
    "mocha-cxlab-report": "npm run mochatest-cxlab ; npm run run-report",
    "mocha-sauce-report": "npm run mochatest-sauce ; npm run run-report",
    "cucumber-local-report": "npm run cucumbertest-local ; npm run run-report",
    "cucumber-cxlab-report": "npm run cucumbertest-cxlab ; npm run run-report",
    "cucumber-sauce-report": "npm run cucumbertest-sauce ; npm run run-report",
    "local": "./node_modules/.bin/wdio ./wdio.conf.js",
    "cxlabs": "npm run connect-adb && ./node_modules/.bin/wdio ./config/wdio.mocha.cxlab.conf.js; npm run run-report"
  },
  "keywords": [
    "webdriverio",
    "typescript"
  ],
  "author": {
    "name": "Thulasiram Siripireddy"
  },
  "license": "ISC",
  "devDependencies": {
    "@types/chai": "^4.1.7",
    "@types/cucumber": "^4.0.5",
    "@types/mocha": "^5.2.5",
    "@types/node": "^10.12.30",
    "@types/request": "^2.48.1",
    "@wdio/allure-reporter": "^5.7.2",
    "@wdio/applitools-service": "^5.7.2",
    "@wdio/cli": "^5.7.1",
    "@wdio/devtools-service": "^5.7.0",
    "@wdio/local-runner": "^5.7.1",
    "@wdio/mocha-framework": "^5.7.0",
    "@wdio/sauce-service": "^5.7.0",
    "@wdio/selenium-standalone-service": "^5.7.0",
    "@wdio/sync": "^5.7.2",
    "appium": "^1.10.1",
    "axe-core": "^3.1.2",
    "axe-reports": "^1.1.11",
    "chai": "^4.2.0",
    "deepmerge": "^3.1.0",
    "nconf": "^0.10.0",
    "prettier": "^1.15.3",
    "request": "^2.88.0",
    "request-promise": "^4.2.2",
    "rimraf": "^2.6.3",
    "swagger-client": "^2.1.9",
    "ts-node": "^7.0.1",
    "tsconfig-paths": "^3.7.0",
    "typescript": "^3.3.3333",
    "wdio-appium-service": "^0.2.3",
    "wdio-chromedriver-service": "^5.0.0",
    "wdio-cucumber-framework": "^2.2.8",
    "wdio-cucumber-reporter": "0.0.2",
    "webdriverio": "^5.7.1"
  },
  "engines": {
    "node": ">=7.6.0"
  },
  "dependencies": {
    "wdio-mochawesome-reporter": "^2.0.1"
  }
}

**Comment by tulasirm** [comment]
Here is the spec file.

import { Eyes, Target } from '@wdio/applitools-service';

describe('My Google Search', () => {
    it('should open the page', () => {
		try {
		browser.url('/')
		const pageTitle = browser.getTitle();
		const viewportSize = browser.getWindowSize();
		Eyes.open(browser, pageTitle, 'My first Javascript visual test!', viewportSize);
		Eyes.check(pageTitle, Target.window());
		Eyes.close();
		}
		finally {
			 Eyes.abortIfNotClosed();
		  }
    })
})

**Comment by tulasirm** [comment]
FYI.. 
initialization error gone after installing latest wdio package, but still i am not successful in getting screenshots in applitools results dashboard

**Comment by tulasirm** [comment]
the latest issue i noticed is 

Stderr:
[0-0] 2019-03-14T22:50:00.094Z ERROR @wdio/sync: TestFailedError: Error: Failed to set viewport size!
    at that._driver.switchTo.frames.then (/Users/prokarma/e2e/node_modules/@wdio/eyes.webdriverio/src/Eyes.js:815:17)
    at ApplitoolsService.beforeTest (/Users/prokarma/e2e/node_modules/@wdio/applitools-service/build/index.js:72:20)
[0-0] 2019-03-14T22:50:09.144Z ERROR @wdio/sync: Error
    at ApplitoolsService.afterTest (/Users/prokarma/e2e/node_modules/@wdio/applitools-service/build/index.js:82:20)

Test Suites:     0 passed, 1 failed, 1 total (100% completed)

**Comment by yuriieasternpeak** [comment]
> the latest issue i noticed is
> 
> Stderr:
> [0-0] 2019-03-14T22:50:00.094Z ERROR @wdio/sync: TestFailedError: Error: Failed to set viewport size!
> at that._driver.switchTo.frames.then (/Users/prokarma/e2e/node_modules/@wdio/eyes.webdriverio/src/Eyes.js:815:17)
> at ApplitoolsService.beforeTest (/Users/prokarma/e2e/node_modules/@wdio/applitools-service/build/index.js:72:20)
> [0-0] 2019-03-14T22:50:09.144Z ERROR @wdio/sync: Error
> at ApplitoolsService.afterTest (/Users/prokarma/e2e/node_modules/@wdio/applitools-service/build/index.js:82:20)
> 
> Test Suites: 0 passed, 1 failed, 1 total (100% completed)

try to run browser in headless mode or you need set less viewport size

**Comment by klamping** [comment]
FYI, this service was ported to the official WebdriverIO v5 repo. Please see https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-applitools-service for future usage and report issues through that repo
